// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GlucoseX.iOS
{
	public partial class GlucoseDataNewEntryNavigationController : UINavigationController
	{
		public GlucoseDataNewEntryNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
