// This file has been autogenerated from a class added in the UI designer.

using System;

using System.Collections.Generic;
using Foundation;
using Robotics.Mobile.Core.Bluetooth.LE;
using UIKit;
using System.Threading.Tasks;

namespace GlucoseX.iOS
{
	public partial class GlucoseDataPageViewController : UIPageViewController
	{

		public GlucoseDataPageViewController (IntPtr handle) : base(handle)
		{
			
		}

		public async override void ViewDidLoad ()
		{
			base.ViewDidLoad();

			View.BackgroundColor = UIColor.White;
		}


		public async override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear(animated);

			Tuple<bool, NSError> tup = await HealthKitProvider.ValidateAuthorizationAsync();

			if (tup.Item1) await SetupDataSource();
		}

		async Task SetupDataSource ()
		{
			GlucoseDataService.Data = await HealthKitProvider.RetrieveGlucoseDataFromHealthAppAsync();

			var initialViewController = Storyboard.Instantiate<GlucoseDataViewController>();

			initialViewController.Data = GlucoseDataService.Data[0];

			DataSource = new GlucosePageViewControllerDataSource (Storyboard.Instantiate<GlucoseDataViewController>());

			SetViewControllers(new [] { initialViewController }, UIPageViewControllerNavigationDirection.Forward, false, null);
		}


		async partial void AddButtonClicked (UIBarButtonItem sender)
		{
			var randomData = GlucoseDataService.GenerateRandomGlucoseData();

			await HealthKitProvider.SaveGlucoseDataToHealthAppAsync(randomData);

			GlucoseDataService.Data = await HealthKitProvider.RetrieveGlucoseDataFromHealthAppAsync();

			var alertViewController = new UIAlertController {
				Title = "Data Sync",
				Message = "Glucose data successfully synced to the Health app database"
			};

			alertViewController.AddAction(UIAlertAction.Create("Awesome!", UIAlertActionStyle.Cancel, obj => DismissViewController(true, null)));

			PresentViewController(alertViewController, true, null);
		}


		public override UIStatusBarStyle PreferredStatusBarStyle ()
		{
			return UIStatusBarStyle.LightContent;
		}
	}
}