// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GlucoseX.iOS
{
	public partial class GlucoseDataViewController : UIViewController
	{

		public GlucoseData Data { get; set; }


		public GlucoseDataViewController (IntPtr handle) : base(handle)
		{
		}


		public override void ViewDidLoad ()
		{
			base.ViewDidLoad();

			if (Data != null) {
				GlucoseValueLabel.Text = Data.Value.ToString();
				GlucoseUnitLabel.Text = Data.Unit;
				GlucoseDateLabel.Text = Data.DateString;
			}
		}
	}
}