// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GlucoseX.iOS
{
	public partial class GlucoseDataNewEntryTableViewController : UITableViewController
	{
		NSDate pickerDate;

		NSDateFormatter formatDate;

		public GlucoseDataNewEntryTableViewController (IntPtr handle) : base(handle)
		{
		}


		public override nfloat GetHeightForRow (UITableView tableView, NSIndexPath indexPath)
		{
			return 44;
		}


		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear(animated);

			updateDateTimeFields();

			DataFieldGlucose.BecomeFirstResponder();

			AddButton.Enabled = true;
		}



		async partial void AddButtonClicked (NSObject sender)
		{
			var data = new GlucoseData {
				Value = int.Parse(DataFieldGlucose.Text),
				Unit = "mg/dL",
				Date = pickerDate.NSDateToDateTime(),
				UserEntered = true
			};

			await HealthKitProvider.SaveGlucoseDataToHealthAppAsync(data);

			DismissViewController(true, null);
		}



		partial void CancelButtonClicked (NSObject sender)
		{
			DismissViewController(true, null);
		}



		partial void DatePickerValueChanged (NSObject sender)
		{
			var picker = sender as UIDatePicker;

			if (picker != null) {

				pickerDate = picker.Date;

				updateDateTimeFields();
			}
		}



		void updateDateTimeFields ()
		{
			if (pickerDate == null) {
				pickerDate = new NSDate ();
			}

			if (formatDate == null) {
				formatDate = new NSDateFormatter ();
			}

			formatDate.DateStyle = NSDateFormatterStyle.Medium;
			formatDate.TimeStyle = NSDateFormatterStyle.None;

			DataFieldDate.Text = formatDate.StringFor(pickerDate);


			formatDate.DateStyle = NSDateFormatterStyle.None;
			formatDate.TimeStyle = NSDateFormatterStyle.Short;

			DataFieldTime.Text = formatDate.StringFor(pickerDate);
		}
	}
}
