// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BloodPressureX
{
	public partial class BloodPressureCvCell : UICollectionViewCell
	{
		public static readonly string ReuseId = "BloodPressureCvCell";

		public BloodPressureCvCell (IntPtr handle) : base(handle)
		{
		}

		public void SetData (BloodPressure bp)
		{
			BloodPressureValueLabel.Text = bp.ValueString;
			BloodPressureDateLabel.Text = bp.DateString;
		}
	}
}
