// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BloodPressureX
{
	public partial class BloodPressureTbc : UITabBarController
	{
		public BloodPressureTbc (IntPtr handle) : base (handle)
		{
		}
	}
}
