// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace BloodPressureX
{
	public partial class HistoryBloodPressureCvc : UICollectionViewController
	{
		// move this
		List<BloodPressure> Data = new List<BloodPressure> ();

		public HistoryBloodPressureCvc (IntPtr handle) : base(handle)
		{
		}

		public async override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear(animated);

			Data = await HealthKit.RetrieveBloodPressureDataFromHealthAppAsync();

			CollectionView.ReloadData();
		}


		public override nint NumberOfSections (UICollectionView collectionView)
		{
			return 1;
		}


		public override nint GetItemsCount (UICollectionView collectionView, nint section)
		{
			return Data.Count;
		}


		public override UICollectionViewCell GetCell (UICollectionView collectionView, NSIndexPath indexPath)
		{
			var cell = collectionView.DequeueReusableCell(BloodPressureCvCell.ReuseId, indexPath) as BloodPressureCvCell;

			var data = Data[Convert.ToInt32(indexPath.Item)];

			cell.SetData(data);

			return cell;
		}


		public override void ItemSelected (UICollectionView collectionView, NSIndexPath indexPath)
		{
			base.ItemSelected(collectionView, indexPath);
		}
	}
}