// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BloodPressureX
{
	public partial class NewBloodPressureVc : UIViewController
	{
		public NewBloodPressureVc (IntPtr handle) : base (handle)
		{
		}
	}
}
