// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BloodPressureX
{
	public partial class RecentBloodPressureCvc : UICollectionViewController
	{
		public RecentBloodPressureCvc (IntPtr handle) : base (handle)
		{
		}
	}
}
